name: Create Tag on Push

on:
  push:
    branches:
      - main

jobs:
  create_tag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Git
        run: git config --global user.email "you@example.com" && git config --global user.name "Your Name"

      - name: Get commit ID
        run: |
          commit_id=$(git rev-parse HEAD)
          echo "Commit ID: $commit_id"

      - name: Create Tag and Push
        run: |
          git tag -a "v$commit_id" -m "Tagging commit $commit_id"
          git push origin "v$commit_id"

      - name: Output Tag Information
        run: echo "Tag created and pushed: v$commit_id"
